Vagrant.configure("2") do |config|
  config.vm.box = "generic/ubuntu2004"
  config.vm.hostname = "registry"
  config.vm.synced_folder "./", "/vagrant", type: "nfs"
  config.vm.network :private_network,
      :libvirt__network_name => "k8s",
      :ip => "192.168.221.100"

  config.vm.provider :libvirt do |q|
    q.memory = 2048
    q.cpus = 1
  end
  
end
