FROM ubuntu:latest
RUN od --format=c --address-radix=n /dev/urandom | tr -d " " | tr -d "\n" | head -c 1950M >> random.random.1
RUN od --format=c --address-radix=n /dev/urandom | tr -d " " | tr -d "\n" | head -c 1950M >> random.random.2
RUN od --format=c --address-radix=n /dev/urandom | tr -d " " | tr -d "\n" | head -c 1950M >> random.random.3
RUN od --format=c --address-radix=n /dev/urandom | tr -d " " | tr -d "\n" | head -c 1950M >> random.random.4
